### ISSUE TITLE
Broken link: panorama.mov

### ISSUE THREAD

**Issue by pancutan** [AndresGalaviz/Football-Player-Tracking#4]
Hi guys
Could you provide a new link for panorama.mov?

Thanks everyone

**Comment by weihuang1979** [comment]
i'm looking for this one as well...

**Comment by pancutan** [comment]
Here it is
[panorama.mov.zip](https://github.com/AndresGalaviz/Football-Player-Tracking/files/1177472/panorama.mov.zip)

In the other hand... any of you where sucessfully compiling this project on Python3.6 ?

**Comment by weihuang1979** [comment]
thanks..  I have not try it yet. Once I have some progress, I will let you
know.

**Comment by gabrielaolinto** [comment]
I'm trying to compile on Python 3.6 too without success. Here it is my error:

bg_delta = cv2.absdiff(gray_bg_img, gray_img)
cv2.error: /tmp/opencv-20171204-57506-1gtts92/opencv-3.3.1/modules/core/src/arithm.cpp:659: error: (-209) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function arithm_op

Someone had the same problem?
Thanks!

**Comment by smilexu** [comment]
if you show the gray_bg_img and gray_img, you will understand the reason.

**Comment by smilexu** [comment]
I spent couple hours to run this project successful based on python 2, opencv 3. But unfortunately, not works very accurate and also see quite lot of hard code, e.g red and blue player.

Anyway, it is a quite good project to help me learning how to use opencv in player detecting.

**Comment by narutmaxorn** [comment]
> I'm trying to compile on Python 3.6 too without success. Here it is my error:
> 
> bg_delta = cv2.absdiff(gray_bg_img, gray_img)
> cv2.error: /tmp/opencv-20171204-57506-1gtts92/opencv-3.3.1/modules/core/src/arithm.cpp:659: error: (-209) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function arithm_op
> 
> Someone had the same problem?
> Thanks!
I'm having the same problem , did you manage to fix it ?
